name: Camera Corner Studios
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73343
title: audio - video - photo - broadcast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#a9233e'
    - '#c3c3c3'
    - '#5f5f5f'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
